#!/usr/bin/env python3
"""批量生成高质量数据"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import json
import time
from datetime import datetime
import uuid

def create_provenance(batch_id: str, generator: str, domain: str = None) -> dict:
    """
    创建数据来源证明（包含AI合成声明）
    """
    domain_disclaimers = {
        "医疗": "This text is synthetically generated by AI. It is based on general medical knowledge and does not originate from any specific real-world patient record or copyrighted material.",
        "金融": "This text is synthetically generated by AI. It is based on general financial knowledge and does not constitute investment advice or originate from any copyrighted financial material.",
        "法律": "This text is synthetically generated by AI. It is based on general legal knowledge and does not constitute legal advice or originate from any copyrighted legal document.",
        "劳动合同": "This text is synthetically generated by AI. It is based on general labor law knowledge and does not constitute legal advice or originate from any copyrighted legal document.",
        "default": "This text is synthetically generated by AI. It does not originate from any copyrighted material or real-world personal data."
    }
    
    disclaimer = domain_disclaimers.get(domain, domain_disclaimers["default"])
    
    return {
        "platform": "PureData",
        "version": "2.2.0",
        "generated_at": datetime.now().isoformat(),
        "batch_id": batch_id,
        "generator": generator,
        "disclaimer": disclaimer,
        "disclaimer_cn": "本文本由AI合成生成，不来源于任何受版权保护的材料或真实个人数据。",
        "license": "CC0-1.0 (Public Domain)",
        "compliance": ["数据安全法", "个人信息保护法", "著作权法"]
    }

print("="*60)
print("批量生成高质量数据")
print("="*60)

from high_quality_generator import HighQualityGenerator, KnowledgeBase

gen = HighQualityGenerator()
KNOWLEDGE = KnowledgeBase.KNOWLEDGE

# 生成配置
domains = ["劳动合同", "人工智能", "医疗", "金融"]
counts = {
    "劳动合同": 500,
    "人工智能": 500,
    "医疗": 500,
    "金融": 500
}

total_generated = 0
all_data = []

for domain in domains:
    count = counts[domain]
    print(f"\n[{domain}] 生成 {count} 条数据...")
    
    try:
        # 获取关键词列表
        keywords = list(KNOWLEDGE.get(domain, {}).keys())
        if len(keywords) < count:
            # 扩展关键词
            keywords = keywords * (count // len(keywords) + 1)
        keywords = keywords[:count]
        
        data = gen.generate_batch(keywords, domain)
        batch_id = f"batch_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        for item in data:
            if item.quality_score >= 0.85:
                quality_tier = "high"
            elif item.quality_score >= 0.75:
                quality_tier = "medium"
            else:
                quality_tier = "low"
            
            item_dict = {
                "id": item.id,
                "word": item.word,
                "text": item.text,
                "category": item.category,
                "source": item.source,
                "quality_score": item.quality_score,
                "quality_tier": quality_tier,
                "timestamp": datetime.now().isoformat(),
                "verified": item.quality_score >= 0.80,
                "provenance": create_provenance(batch_id, "high_quality_batch", domain)
            }
            all_data.append(item_dict)
        
        total_generated += len(data)
        print(f"  完成: {len(data)} 条")
        
    except Exception as e:
        import traceback
        print(f"  错误: {e}")
        traceback.print_exc()

# 保存到文件
output_file = f"outputs/batch_{total_generated}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
os.makedirs("outputs", exist_ok=True)

with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(all_data, f, ensure_ascii=False, indent=2)

print(f"\n{'='*60}")
print(f"总计生成: {total_generated} 条")
print(f"保存到: {output_file}")
print(f"{'='*60}")
